### ISSUE TITLE
No host aliases for docker compose services when deployed to cluster.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#106]
### Describe the bug

When you have docker compose services defined:

```
      docker:
        enabled: true
        compose:
          services:
            initializr-workshop:
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.0
              ports:
                - "127.0.0.1:8080:8080"
```

and deploy the workshop to local docker environment, then the service is accessible from inside of the container using as hostname the name of the service, eg., `initializr-workshop`, along with the exposed port.

When deploying the same workshop to a Kubernetes cluster the services run in the same network namespace and thus services are accessed via `localhost` using the exposed port.

In the case of wanting to expose such a service via an ingress you would use:

```
    ingresses:
      - name: initializr
        protocol: http
        host: initializr-workshop
        port: 8080
```

This however only works for docker deployment, unless you patch the workshop definition to add `hostAliases`.

```
  session:
    patches:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - initializr-workshop
```

There was previously an attempt to add host aliases automatically, but it was commented out as wasn't working as intended. The code for adding host aliases should be reviewed and fixed if possible.
