### ISSUE TITLE
Provide way to declare owner references between resource objects.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#118]
### Is your feature request related to a problem? Please describe.

When using an `App` resource for `kapp-controller` in `environment.objects`, `session.objects`, or `resource.objects`, with deployment to the current cluster (not virtual cluster), it is required to provide a service account with the required access privileges to the cluster. This service account will be used when creating and later deleting of resources from the cluster by `kapp-controller`. In the workshop definition you thus end up with something like:

```
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kapp-installer
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kapp-installer-$(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: kapp-installer
          namespace: $(session_namespace)
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: my-app
      spec:
        serviceAccountName: kapp-installer
```

The problem is that on deletion, the service account can get deleted before `kapp-controller` can process `App` resource deletion, resulting in `kapp-controller` failing.

Where everything installed due to the `App` was deployed inside of `$(session_namespace)`, one could add to the `App` the `noopDelete: true` setting, meaning `kapp-controller` should not try and cleanup any resources, but because they were all inside of `$(session_namespace)` they would get deleted anyway.

Even where `App` gets stuck in the deleting phase and not using `noopDelete: true`, the mechanism in Educates to unstick namespaces that can't be deleted, ie., remove finalizers on resources in namespaces created by Educates, will still see `App` being removed.

Neither of these are sufficient thought for where the `App` results in cluster scoped resources being created. This is because there are no owner references declared between the Educates environment or session scoped resources, so those cluster scoped resources created by `App` will remain.

Where the cluster scoped resources left behind are somehow named based on the environment or session name, if the workshop environment is deleted and recreated, with same environment name, and thus also same session names, the deployment of `App` fails the subsequent time as the cluster scoped resources already exists.

### Describe the solution you'd like

One possible solution may be to allow resources in the workshop definition to define partial owner references. Eg.,

```
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kapp-installer
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kapp-installer-$(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: kapp-installer
          namespace: $(session_namespace)
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: my-app
        ownerReferences:
        - apiVersion: v1
          blockOwnerDeletion: true
          controller: false
          kind: ServiceAccount
          name: kapp-controller
        - apiVersion: rbac.authorization.k8s.io/v1
          blockOwnerDeletion: true
          controller: false
          kind: ClusterRoleBinding
          name: kapp-installer-$(session_namespace)
      spec:
        serviceAccountName: kapp-installer
        ...
```

This allows one to state that the `App` is effectively owned by both the service account and the cluster role binding and as a result, the service account and cluster role binding cannot be deleted until the `App` has been deleted.

What is missing is the `uid` fields for the parent resource object in the owner references, which the Educates operator would need to work out and insert.

Note that this would still depend on foreground deletion being specified when owning workshop environment or session is being deleted, as block owner deletion only comes into play in that case.

### Additional information

Note that the owner reference should possibly only be added where the owner is created as part of the same workshop environment or session. That is, it should check for annotations:

```
    training.educates.dev/component: environment
    training.educates.dev/environment.name: educates-cli-w01
    training.educates.dev/policy.engine: none
    training.educates.dev/policy.name: privileged
    training.educates.dev/portal.name: educates-cli
    training.educates.dev/workshop.name: educates-cli--lab-installing-educates-6d3f920
```

in the possible owner.

If don't do this and allowed attaching to arbitrary objects, could interfere with stuff outside of the context of the Educates workshop.
