### ISSUE TITLE
Allow one to set target of proxy ingress as being insecure.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#123]
### Is your feature request related to a problem? Please describe.

I want to be able to specify an additional ingress where the target host uses a self signed certificate.

```
    ingresses:
    - name: console
      host: console-openshift-console.$(ingress_domain)
      protocol: https
    dashboards:
    - name: OpenShift
      url: $(ingress_protocol)://console-$(session_hostname)/
```

### Describe the solution you'd like

Add a `secure` property to `ingresses`. This would map through to option of same name in `http-proxy-middleware` used to proxy the connection. https://www.npmjs.com/package/http-proxy-middleware

This would then allow:

```
    ingresses:
    - name: console
      host: console-openshift-console.$(ingress_domain)
      protocol: https
      secure: false
    dashboards:
    - name: OpenShift
      url: $(ingress_protocol)://console-$(session_hostname)/
```
