### ISSUE TITLE
Allow target platform architectures to be specified for workflow_dispatch.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#140]
### Is your feature request related to a problem? Please describe.

Building arm64 images takes forever on GitHub actions as the builds occur under QEMU. Want a way of restricting builds to just amd64 when triggering GitHub actions manually using workflow_dispatch trigger.

### Describe the solution you'd like

Modify GitHub actions workflow so uses:

```
  workflow_dispatch:
    inputs:
      platforms:
        type: choice
        description: Platforms to build
        options: 
        - linux/amd64
        - linux/arm64
        - linux/amd64,linux/arm64
```

Default to `linux/amd64` so quicker, but still allow selection of other options.

This would then be used in setting platforms later, in place of:

```
      - name: Build and push ${{matrix.image}} image
        uses: docker/build-push-action@v3
        with:
          context: workshop-images/${{matrix.image}}
          platforms: linux/amd64,linux/arm64
          build-args: |
            IMAGE_REPOSITORY=ghcr.io/${{github.repository_owner}}
            BASE_IMAGE_NAME=educates-base-environment
            PACKAGE_VERSION=${{env.REPOSITORY_SHA_TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: ${{steps.meta.outputs.tags}}
          push: true
```

Note that will need use an intermediary environment variable as input wouldn't exist when triggered via tag.
