### ISSUE TITLE
Release package PR placing package files in wrong location.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#156]
### Describe the bug

The GitHub action used:

```
      - name: Restore educates-cluster-essentials.yaml
        uses: actions/download-artifact@v3
        with:
          name: educates-cluster-essentials-${{env.REPOSITORY_TAG}}.yaml
          path: package-repository/packages/cluster-essentials.educates.dev/educates-cluster-essentials-${{env.REPOSITORY_TAG}}.yaml

      - name: Restore educates-training-platform.yaml
        uses: actions/download-artifact@v3
        with:
          name: educates-training-platform-${{env.REPOSITORY_TAG}}.yaml
          path: package-repository/packages/training-platform.educates.dev/educates-training-platform-${{env.REPOSITORY_TAG}}.yaml
```

to restore package files when creating the PR to add package files back to the `develop` branch.

This though resulted in a directory named `package-repository/packages/cluster-essentials.educates.dev/educates-cluster-essentials-${{env.REPOSITORY_TAG}}.yaml` containing `educates-cluster-essentials-${{env.REPOSITORY_TAG}}.yaml`.

This only occurred for some reason when done on main code repo and not when test on a fork.

Change to:

```
      - name: Restore educates-cluster-essentials.yaml
        uses: actions/download-artifact@v3
        with:
          name: educates-cluster-essentials-${{env.REPOSITORY_TAG}}.yaml
          path: package-repository/packages/cluster-essentials.educates.dev/

      - name: Restore educates-training-platform.yaml
        uses: actions/download-artifact@v3
        with:
          name: educates-training-platform-${{env.REPOSITORY_TAG}}.yaml
          path: package-repository/packages/training-platform.educates.dev/
```

to try and guarantee behaviour around what directory will be.
