### ISSUE TITLE
Add back builtin support for OpenShift web console.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#166]
### Is your feature request related to a problem? Please describe.

When a workshop is deployed to OpenShift, and is targeting OpenShift features, it would be preferable to have access to the OpenShift web console rather than standard Kubernetes dashboard.

### Describe the solution you'd like

Add back ability to set `vendor` under `applications.console` to `openshift`.

Also provide an option which can be set which results in download of the `oc` client corresponding to the OpenShift version, from the download server hosted within the OpenShift cluster itself, into the workshop session.

### Describe alternatives you've considered

The OpenShift web console can be added via a side car by adding a patch in the workshop definition, but this puts complexity on the user.

The `oc` client could be provided with the workshop base image rather than downloading it from the clusters own download server, but this would add extra bloat to the workshop base image as would need to support multiple versions like do with `kubectl`.

**Comment by GrahamDumpleton** [comment]
A way of doing this through the workshop definition for now is as follows:

```
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-openshift-testing"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/lab-openshift-testing-files:$(workshop_version)"
  workshop:
    files:
      includePaths:
      - /workshop/**
      - /templates/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: xconsole
      host: console-openshift-console.$(ingress_domain)
      protocol: https
    - name: console
      port: 10083
    dashboards:
    - name: OpenShift
      url: $(ingress_protocol)://console-$(session_hostname)/
    patches:
      containers:
      - name: console
        image: quay.io/openshift/origin-console:4.15
        command:
        - "/opt/bridge/bin/bridge"
        env:
        - name: BRIDGE_K8S_MODE
          value: in-cluster
        - name: BRIDGE_LISTEN
          value: http://0.0.0.0:10083
        - name: BRIDGE_BASE_PATH
          value: "/"
        - name: BRIDGE_PUBLIC_DIR
          value: "/opt/bridge/static"
        - name: BRIDGE_USER_AUTH
          value: disabled
        - name: BRIDGE_BRANDING
          value: openshift
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: cluster-token
          readOnly: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: openshift-user
      rules:
      - apiGroups:
        - project.openshift.io
        resources:
        - projects
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - image.openshift.io
        resources:
        - imagestreams
        verbs:
        - create
      - apiGroups:
        - build.openshift.io
        resources:
        - builds/details
        verbs:
        - update
      - apiGroups:
        - build.openshift.io
        resources:
        - builds
        verbs:
        - get
      - apiGroups:
        - build.openshift.io
        resources:
        - buildconfigs
        - buildconfigs/webhooks
        - builds
        verbs:
        - create
        - delete
        - deletecollection
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - build.openshift.io
        resources:
        - builds/log
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - build.openshift.io
        resources:
        - buildconfigs/instantiate
        - buildconfigs/instantiatebinary
        - builds/clone
        verbs:
        - create
      - apiGroups:
        - apps.openshift.io
        resources:
        - deploymentconfigs
        - deploymentconfigs/scale
        verbs:
        - create
        - delete
        - deletecollection
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - image.openshift.io
        resources:
        - imagestreams/status
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - image.openshift.io
        resources:
        - imagestreamimages
        - imagestreammappings
        - imagestreams
        - imagestreamtags
        - imagetags
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - image.openshift.io
        resources:
        - imagestreams/layers
        verbs:
        - get
      - apiGroups:
        - route.openshift.io
        resources:
        - routes
        verbs:
        - create
        - delete
        - deletecollection
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - route.openshift.io
        resources:
        - routes/custom-host
        verbs:
        - create
      - apiGroups:
        - route.openshift.io
        resources:
        - routes/status
        verbs:
        - get
        - list
        - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: openshift-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: openshift-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
```
