### ISSUE TITLE
Add labels for categorizing training portals.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#169]
### Is your feature request related to a problem? Please describe.

I want a way to categorize training portals so I might have a way of aggregating workshops from multiple training portals to display in a front end portal. I don't want to use Kubernetes labels because of restrictions on names and values.

### Describe the solution you'd like

Want to be able to say:

```
spec:
  portal:
    labels:
      name-1: value
      name-2: value
```
