### ISSUE TITLE
Path based routing when using workshop ingresses.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#285]
### Is your feature request related to a problem? Please describe.

When specifying an additional ingress point for a workshop session, under a single ingress host name, I want to be able to route to different backend services based on a path prefix.

### Describe the solution you'd like

I want to be able to have duplicate ingress entries with the same name, but where `path` can be defined so that only requests with that path prefix are routed to that backend.

```
spec:
  session:
    ingresses:
    - name: application
      port: 8081
      path: /api
    - name: application
      port: 8080
```

Note that the ingress rules would be processed in order and thus would be up to use to ensure that more deeply nested URL path's precede catch all for host. An entry which doesn't specific `path`, would have an effective default of `/`.

End result would thus be if request was against `application-$(session_name).$(ingress_domain)/api` that it would be proxied to local process listening on port 8081. A request against `application-$(session_name).$(ingress_domain)/` would be proxied to local process listening on port 8080.

With addition of this mechanism, a `pathRewrite` rule should also be supported.

```
spec:
  session:
    ingresses:
    - name: application
      port: 8081
      path: /api
      pathRewrite:
      - pattern: "^/api/"
        replacement: "/"
    - name: application
      port: 8080
```

### Describe alternatives you've considered

One could do this by creating your own backend proxy service using envoy, but that would be a lot more work.
