### ISSUE TITLE
Educates vcluster feature not working with Cillium CNI

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#310]
### Describe the bug

When a Kubernetes cluster has Cillium as CNI, educates' vcluster feature seems not to work fine. Investigate why.

### Additional information

[Reference conversation in kubernetes slack](https://kubernetes.slack.com/archives/C05UWT4SKRV/p1708948275299299)

**Comment by GrahamDumpleton** [comment]
You seem to have made multiple changes but you don't call them out explicitly and explain precisely why needed. Can you confirm the following.

1 - You believe you need to add:

```
  - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
```

2 - You believe the following should be dropped.

```
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
```

I can understand 2 being an issue if your system is putting DNS on 169.254.169.254. There has been concerns about this in the past with:

* https://github.com/educates/educates-training-platform/issues/597

since the way things are you can't override the block on 169.254.169.254.

Can you confirm that your DNS is on IP address 169.254.169.254?

We have talked before about changing the network policy rule to still allow port 53 access on 169.254.169.254 as we had situation come up before where it was an issue, or inferred it could be an issue in reading docs for how that special IP is used by some infrastructure providers (but hadn't seen it first hand as yet). We didn't link that to the vcluster on Cilium issue though.

Since I am not very good at network policies I didn't think though about using namespace/pod selector to target allowing DNS though, and was still think about using the IP.

That said, if the allow to DNS is added, can't the general block of 169.254.169.254 still be okay. I thought once it found a rule that said egress was okay, that would stop. So it shouldn't fall through to later general block of that IP. So am not sure that 2 above is needed. If you still have 2 above, along with the DNS allow, does it work?
