### ISSUE TITLE
Make javascript injection easier for things like cookies consent, or others

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#366]
### Is your feature request related to a problem? Please describe.

Sometimes it's required to add additional javascript scripts to the Educates Platform to allow for things like cookie consent due to GDPR laws. Currently you can add these to a theme, but it's maybe overly complicated.

### Describe the solution you'd like

Investigate what kind of javascripts would need to be injected (also if CSPs would need to be modified) and provide an easy way to set these up. An example of scripts could be https://cookieconsent.orestbida.com/

### Additional information

Current Kubernetes slack thread with some information about this: https://kubernetes.slack.com/archives/C05UWT4SKRV/p1715589756629829

**Comment by GrahamDumpleton** [comment]
First possible change suggest is that currently you can specify `Secret` resource with theme files.

```
apiVersion: v1
kind: Secret
metadata:
  name: workshops.example.com-theme
  namespace: default
stringData:
  workshop-dashboard.html: ""
  workshop-dashboard.css: ""
  workshop-dashboard.js: ""
  workshop-instructions.html: ""
  workshop-instructions.js: ""
  workshop-instructions.css: ""
  workshop-started.html: ""
  workshop-finished.html: ""
  training-portal.html: ""
  training-portal.js: ""
  training-portal.css: ""
```

The `.html` file is embedded directly in head section of pages.

The `.css` file is included into the head section using a `link` element.

The `.js` file is included at the bottom of the HTML body element using a `script` element.

Right now everything has to be in the one file which is not convenient when needing to include multiple files from third party packages along with your own customisations.

To enable having multiple files, have convention whereby for example in addition to `training-portal.html`, you can have files `training-portal-nnn.html` where `nnn` is integer number. Where such files exist they will be embedded/included at appropriate point in sorted order.

Thus `Secret` might be defined as:

```
```
apiVersion: v1
kind: Secret
metadata:
  name: workshops.example.com-theme
  namespace: default
stringData:
  training-portal-1.html: "..."
  training-portal-2.html: "..."
  training-portal-1.js: ""
  training-portal-2.js: ""
  training-portal-1.css: ""
  training-portal-2.css: ""
```

If variant with no number is still provided, it would be embedded/included before the numbered ones.
