### ISSUE TITLE
Can't override workshop/terminal layout from inside of session.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#370]
### Describe the bug

The workshop definition is injected into the workshop session container and is used to control certain aspects of how the workshop session dashboard is rendered. This includes how many terminal panes, dashboards tabs enabled, ingress proxy definitions etc.

```
spec:
  title: "Workshop"
  description: "Workshop."
  session:
    applications:
      terminal:
        enabled: true
        layout: split
  ingresses:
  - name: application
    port: 8080
``` 

In the past, some information such as workshop and terminal layout was passed to the container via environment variables. To support backward compatibility code such as the following is used.

```
WORKSHOP_LAYOUT=${WORKSHOP_LAYOUT=`workshop-definition -r '(.spec.session.applications.workshop.layout // "default")'`}
export WORKSHOP_LAYOUT

TERMINAL_LAYOUT=${TERMINAL_LAYOUT=`workshop-definition -r '(.spec.session.applications.terminal.layout // "default")'`}
export TERMINAL_LAYOUT
```

Even when the variable `TERMINAL_LAYOUT` is set to an empty string, this code is not falling back to using the value from the injected workshop definition file, thus preventing override of these layout settings inside of the container by modifying the workshop definition before the dashboard is started.

Should drop passing of these environment variables from the operator via the deployment and change code in workshop image (`start-gateway` script) to:

```
WORKSHOP_LAYOUT=$(workshop-definition -r '(.spec.session.applications.workshop.layout // "default")')
export WORKSHOP_LAYOUT

TERMINAL_LAYOUT=$(workshop-definition -r '(.spec.session.applications.terminal.layout // "default")')
export TERMINAL_LAYOUT
```
