### ISSUE TITLE
CLI config missing ability to set REST API client identifiers.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#421]
### Describe the bug

When using the CLI to install Educates, the config file is missing ability to specify:

```
trainingPortal:
  clients:
    robot:
      id: "robot-id"
      secret: "robot-secret"
```

Results in error:

```
Error: unable to parse installation config file developer-testing/educates-installer-values.yaml: yaml: unmarshal errors:
  line 23: field clients not found in type config.TrainingPortalConfig
```
