### ISSUE TITLE
Robot credentials not passed through if admin credentials were not set.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#422]
### Describe the bug

When using CLI, if config file had:

```
trainingPortal:
  credentials:
    #admin:
    #  username: "educates"
    #  password: "my-pasword"
    robot:
      username: "robot@educates"
      password: "my-pasword"
```

then `robot` credentials would not be passed through if `admin` credentials were not supplied at the same time.
