### ISSUE TITLE
The changeOrigin option for ingress has been lost from Workshop CRD.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#442]
### Describe the bug

Documentation says one can set `changeOrigin` for an ingress:

```
spec:
  session:
    ingresses:
    - name: application
      protocol: http
      host: service.$(session_namespace).svc.$(cluster_domain)
      changeOrigin: false
      port: 8080
```

This is rejected though because `changeOrigin` is missing from the Workshop CRD.

The code in the dashboard session proxy does actually support `changeOrigin`, so the property has been lost from the CRD at some point.
