### ISSUE TITLE
Documentations doesn't cover that can add labels to a portal.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#469]
### Describe the bug

A `TrainingPortal` resource can have labels independent to Kubernetes labels. The documentation doesn't seem to mention this.

```
spec:
  portal:
    labels: {}
```

Note that this is different to ability to add labels to specific workshops hosted by a training portal.

```
spec:
  portal:
    workshop:
      defaults:
        labels:
        - name: difficulty
          value: easy
  workshops:
  - name: lab-asciidoc-sample
    labels:
    - name: difficulty
      value: hard
  - name: lab-markdown-sample
```
