### ISSUE TITLE
Ability to use labels on a portal is not documented.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#542]
### Is your feature request related to a problem? Please describe.

The docs talking about overriding labels for workshops listed in `TrainingPortal`, but do not describe `labels` for a portal itself.

Note that not talking about Kubernetes metadata labels, but Educates specific labels.

```
spec:
  portal:
    labels:
    - name: environment
      value: staging
```

### Describe the solution you'd like

Add docs.
