### ISSUE TITLE
Add annotation for external-dns services, ingress configuration so only creates resources with it

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#586]
### Is your feature request related to a problem? Please describe.

Currently we are monitoring all services (and previously ingresses and httpproxies). We currently only set up a wildcard dns for envoy service.
There's no way, other than altering the envoy service to create a DNS entry at will.

### Describe the solution you'd like

It'll be nice if we could monitor back ingresses and configure external dns with an annotation (like they do in this [issue](https://github.com/kubernetes-sigs/external-dns/issues/4430) so that if we want, we could deploy an ingress that would create a CNAME on the DNS. This way, we can automate load balancing of lookup clusters via a CNAME that is automated by deploying a resource on the cluster.

**Comment by jorgemoralespou** [comment]
Setting this annotation on Ingresses `external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only` will only create DNS for the ingresses that also have the annotation `external-dns.alpha.kubernetes.io/hostname=nginx.example.org.`

This can be applied in different ways:
- Modifying educates source code to have this annotation hard coded
- Allowing educates to have in configuration additional annotations for the resources it creates
- Having a kyverno ClusterPolicy defined (e.g. below)

Ideally we should aim for second or third options. If third option, we could have a set of kyverno policies shipped with Educates that can be enabled/disabled by configuration, to make installs easier.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-external-dns-annotation-to-educates-ingresses
  annotations:
    policies.kyverno.io/title: Add external-dns annotation to Ingresses in Educates namespaces
    policies.kyverno.io/description: >-
      Mutates any Ingress in an Educates namespace that carries the label key
      training.educates.dev/component (any value) to add the annotation
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only.
spec:
  rules:
    - name: add-ingress-hostname-source-annotation
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaceSelector:
                matchExpressions:
                  - key: training.educates.dev/component
                    operator: Exists
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(external-dns.alpha.kubernetes.io/ingress-hostname-source): annotation-only
```
