### ISSUE TITLE
HTTPS redirect should not be forced when clusterIngress.protocol is overridden to https.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#588]
### Describe the bug

When a front end router is terminating HTTPS, but Educates is deployed using only HTTP with no wildcard certificate, one would override `protocol` to be `https` as in:

```
      clusterIngress:
        domain: grumpys.computer
        protocol: https
```

This is resulting in annotations being added to ingresses:

```
   annotations:                                                                                                                                                                                                                      
     ingress.kubernetes.io/force-ssl-redirect: "true"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

This is wrong, because when the ingress router then receives the request as HTTP, it forces a redirect to HTTPS without even forwarding the request onto the training portal or session. You then get in a redirect loop.

The redirect annotations should not be added in this case where Educates is not setup to be secure but protocol is set to be "https". It should be left up to the external router which is termination HTTPS connections to trigger a redirect from HTTP to HTTPS.

### Additional information

_No response_
