### ISSUE TITLE
Upgrade Kyverno version.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#59]
Note that need to address:

```
Warning: Validation failure actions enforce/audit are deprecated, use Enforce/Audit instead.
```

This is because of settings like:

```
              validationFailureActionOverrides:
                description: ValidationFailureActionOverrides is a Cluster Policy
                  attribute that specifies ValidationFailureAction namespace-wise.
                  It overrides ValidationFailureAction for the specified namespaces.
                items:
                  properties:
                    action:
                      description: ValidationFailureAction defines the policy validation
                        failure action
                      enum:
                      - audit
                      - enforce
                      - Audit
                      - Enforce
                      type: string
```

Must use title case for names from 1.10 onwards.

Note that workshop definition mirrors lower case versions with:

```
                            rules:
                              type: object
                              properties:
                                action:
                                  type: string
                                  enum:
                                  - enforce
                                  - audit
                                  default: enforce
```

so need to determine whether this also needs to change if value flows through.
