### ISSUE TITLE
When embedding of workshop is disabled gateway process crashes.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#71]
### Project version

2.6.0

### Describe the bug

When workshop is disabled:

```
spec:
  session:
    applications:
      workshop:
        enabled: false
```

the gateway process is failing to start up and workshop pod goes into crash loop backoff.

### Reproduction steps

Disable embedding of workshop instructions.

### Expected behavior

Shouldn't fail.
