### ISSUE TITLE
In 2.6.0 the host property of an additional ingress was made required when shouldn't.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#72]
### Project version

2.6.0

### Describe the bug

Prior to 2.6.0, the `host` property of an ingress definition was optional and would default to `localhost`. The custom resource definition of `Workshop` is now marking it as a required field when it shouldn't have.

### Reproduction steps

Use a workshop definition like:

```
spec:
  session:
    ingresses:
    - name: jupyter
      port: 8888
```

### Expected behavior

Should default host to `localhost` if not specified and field should not be required.
