### ISSUE TITLE
Secret copier/exporter fails to update secret if secret didn't have any data in it.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#73]
### Project version

2.6.2

### Describe the bug

When using `SecretExporter` saw the error in secrets manager logs of:

```
│ ERROR:kopf.objects:Timer 'secretexporter_reconcile' failed with an exception. Will retry.                                  │
│ Traceback (most recent call last):                                                                                         │
│   File "/opt/app-root/venv/lib64/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_o │
│ nce                                                                                                                        │
│     result = await invoke_handler(                                                                                         │
│   File "/opt/app-root/venv/lib64/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler    │
│     result = await invocation.invoke(                                                                                      │
│   File "/opt/app-root/venv/lib64/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke           │
│     await asyncio.shield(future)  # slightly expensive: creates tasks                                                      │
│   File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run                                               │
│     result = self.fn(*self.args, **self.kwargs)                                                                            │
│   File "/opt/app-root/src/handlers/secretexporter.py", line 23, in secretexporter_reconcile                                │
│     reconcile_config(name, body)                                                                                           │
│   File "/opt/app-root/src/handlers/secretcopier_funcs.py", line 230, in reconcile_config                                   │
│     update_secrets(namespace_item.name, rules)                                                                             │
│   File "/opt/app-root/src/handlers/secretcopier_funcs.py", line 510, in update_secrets                                     │
│     update_secret(name, rule)                                                                                              │
│   File "/opt/app-root/src/handlers/secretcopier_funcs.py", line 482, in update_secret                                      │
│     and source_secret_item.obj["data"] == target_secret_item.obj.get("data", {})                                           │
│ KeyError: 'data'                                                                                                           │
```

This occurred when the secret didn't container any `data` in it, but may only arise when attempting to update the secret due to a rule change.

So operator is not tolerant of there being no data in the secret.

This possibly also affects `SecretCopier`.

### Reproduction steps

Create an empty secret:

```
k create secret generic xxx -n default
```

Create an `SecretExporter` rule of:

```
apiVersion: secrets.educates.dev/v1beta1
kind: SecretExporter
metadata:
  name: xxx
  namespace: default
spec:
  rules:
  - targetNamespaces:
      nameSelector:
        matchNames:
        - "*"
    copyAuthorization:
      sharedSecret: my-secret
```

In another namespace create a `SecretImporter`:

```
apiVersion: secrets.educates.dev/v1beta1
kind: SecretImporter
metadata:
  name: xxx
  namespace: other-namespace
spec:
  copyAuthorization:
    sharedSecret: my-secret
```

If don't see error immediately, change the original `SecretExporter` to trigger an update. Eg. to:

```
apiVersion: secrets.educates.dev/v1beta1
kind: SecretExporter
metadata:
  name: xxx
  namespace: default
spec:
  rules:
  - targetNamespaces:
      nameSelector:
        matchNames:
        - "!kube-*"
    copyAuthorization:
      sharedSecret: my-secret
```

### Expected behavior

Shouldn't fail when no `data` in a secret, whether that be source or target secret.
